Repository skanehira/docui, pull requests merged in 2019-03, with the labels that each got.

#104 Update Golang Docker image version.
  .circleci/config.yml
Labels: improvement

#106 Fix CI-failed `go get github.com/golang/lint/golint`
  .circleci/config.yml
Labels: bug

#111 Update golang image version.
  .circleci/config.yml
Labels: improvement

#112 Update Docker version.
  .circleci/config.yml
Labels: improvement

#113 Add installation method for Linux distributions other than CentOS.
  wiki.md
Labels: document
